### ISSUE TITLE
Install failed (INSTALL_FAILED_VERSION_DOWNGRADE)

### ISSUE THREAD

**Issue by Starnight91** [j-hc/revanced-magisk-module#489] opened 2024-08-22 07:37 UTC
**DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo

Use issues only to report bugs of the rvmm builder or the modules

I have a problem.
Install always work but since my kast update of my firmware, it has this error :

INSTALL_FAILED_VERSION_DOWNGRADE. Uninstalling...
Failure [not installed for 0]

What can I do ?

**Comment by j-hc** [comment] 2024-08-22 13:36
that happens because the installed version of the system app is higher than the module version.
you could wait until a higher version is supported and use the non-root microg for the time being.

**Comment by pan0rozowy** [comment] 2024-08-27 18:26
I had the same problem today
uninstal youtube from /product/app/youtube/youtube.apk
you can use
https://github.com/sunilpaulmathew/De-Bloater
you may need to reinstall the original youtube to use this app

**Comment by sudanking** [comment] 2024-08-27 20:08
I tried to uninstall it manually using twrp but I couldn't... No debloater on APatch working.
Any suggestions?!

**Comment by Othmane-ElAlami** [comment] 2024-08-28 08:59
Try uninstalling it using [Lucky Patcher](https://www.luckypatchers.com/download/)

**Comment by sudanking** [comment] 2024-08-28 10:39
> Try uninstalling it using [Lucky Patcher](https://www.luckypatchers.com/download/)

No luck...
It's says removed, but it comes back after reboot.
It's in product/app/YouTube folder as apk

**Comment by ramanveerji** [comment] 2024-08-28 11:57
> > Try uninstalling it using [Lucky Patcher](https://www.luckypatchers.com/download/)
> 
> No luck...
> It's says removed, but it comes back after reboot.
> It's in product/app/YouTube folder as apk

Uninstall updates for YouTube app. You have updated your YouTube app.

**Comment by sudanking** [comment] 2024-08-28 12:33
> > > Try uninstalling it using [Lucky Patcher](https://www.luckypatchers.com/download/)
> > 
> > No luck...
> > It's says removed, but it comes back after reboot.
> > It's in product/app/YouTube folder as apk
> 
> Uninstall updates for YouTube app. You have updated your YouTube app. 

I uninstall YT totally, but the only option is installing the newer version 19.17.34 from source in rom located in product/app/YouTube/YouTube.apk

 I installed the latest firmware update (OnePlus 12 OOS 14.840) yesterday and that updated the YT to version higher than revanced use and I cannot remove it either from the system.

I tried with twrp, but it is not there... It's appear only after system work. As it's a bundle with system rom.

Is there any way to remove system package from original firmware?

**Comment by ramanveerji** [comment] 2024-08-28 12:45
> > > > Try uninstalling it using [Lucky Patcher](https://www.luckypatchers.com/download/)
> > > 
> > > No luck...
> > > It's says removed, but it comes back after reboot.
> > > It's in product/app/YouTube folder as apk
> > 
> > Uninstall updates for YouTube app. You have updated your YouTube app. 
> 
> I uninstall YT totally, but the only option is installing the newer version 19.17.34 from source in rom located in product/app/YouTube/YouTube.apk
> 
>  I installed the latest firmware update (OnePlus 12 OOS 14.840) yesterday and that updated the YT to version higher than revanced use and I cannot remove it either from the system.
> 
> I tried with twrp, but it is not there... It's appear only after system work. As it's a bundle with system rom.
> 
> Is there any way to remove system package from original firmware?

Search for universal android debloater gui on GitHub.

**Comment by Othmane-ElAlami** [comment] 2024-08-28 12:51
You mentioned attempting to uninstall it from TWRP, but could you specify which folders you were trying to find and delete?

**Comment by sudanking** [comment] 2024-08-28 13:27
> You mentioned attempting to uninstall it from TWRP, but could you specify which folders you were trying to find and delete?

I mount product
No such YouTube folder in product/app

I tried system and vendor 
But didn't find YouTube folder too!

**Comment by pan0rozowy** [comment] 2024-08-28 13:35
![Screenshot_2024-08-28-15-34-40-29_e66e28f718147b6e7216efe19a1092f5.jpg](https://github.com/user-attachments/assets/46721c2d-c2e2-438c-a6aa-86d3253167ca)

**Comment by Othmane-ElAlami** [comment] 2024-08-28 14:28
![image](https://github.com/user-attachments/assets/afa8015e-97e2-4a69-ab8f-84ffb8be5756)

To manually uninstall an app, you should delete its folders located in `/data/data/`, `/data/user/0/`, and `/data/app/`. You can find the exact folder name using Lucky Patcher. Additionally, you can remove the YouTube APK from `/product/app/` by using a file manager that supports root access.

**Comment by sudanking** [comment] 2024-08-28 15:49
> ![image](https://github.com/user-attachments/assets/afa8015e-97e2-4a69-ab8f-84ffb8be5756)
> 
> To manually uninstall an app, you should delete its folders located in `/data/data/`, `/data/user/0/`, and `/data/app/`. You can find the exact folder name using Lucky Patcher. Additionally, you can remove the YouTube APK from `/product/app/` by using a file manager that supports root access.

I tried to delete product/app/YouTube/YouTube.apk with file manager with root access but no thing deleted!
![Screenshot_2024-08-28-19-41-49-40_83ceefc07bf7d3f049298861e11860bc.jpg](https://github.com/user-attachments/assets/8b390675-dcba-497c-bb92-d953d89856b2)


I tried to delete app with LP but it is never deleted 
![Screenshot_2024-08-28-19-45-25-21_7f6ecc17e32366f17144ac3a2ff1b3dc.jpg](https://github.com/user-attachments/assets/0c05c5a1-0f29-4557-9133-043cd2157e1c)



I tried to delete it with temux with su... Still no luck!
![Screenshot_2024-08-28-19-44-15-05_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/user-attachments/assets/f42cc6a9-e45e-45f1-bf5a-76b70ba32fc0)

In APatch it show this error after reboot:
![Screenshot_2024-08-28-19-40-50-45_26ccd656f4ada08d09da6514b90ed2c0.jpg](https://github.com/user-attachments/assets/c479a729-b4be-4091-a0d5-4534f1857199)

**Comment by TheMartyMan** [comment] 2024-08-29 18:28
Same phone, same problem. I have also tried everything so i'd wait for an update. Thanks guys.

**Comment by arcinin1** [comment] 2024-09-01 14:55
I managed to make it work, first I completely removed YouTube using Lucky Patcher, then I disabled Google Play Store, installed again Revanced 19.16 from this repo and then it worked.
Also planning on installing Zygisk Detach so Google won't mess up my setup.

**Comment by Othmane-ElAlami** [comment] 2024-09-07 00:16
> I managed to make it work, first I completely removed YouTube using Lucky Patcher, then I disabled Google Play Store, installed again Revanced 19.16 from this repo and then it worked. Also planning on installing Zygisk Detach so Google won't mess up my setup.

Can you share in details what you did please? Because I disabled Google Play Store and removed YouTube using Lucky Patcher but whenever I reboot I find it again

**Comment by arcinin1** [comment] 2024-09-07 00:55
> > I managed to make it work, first I completely removed YouTube using Lucky Patcher, then I disabled Google Play Store, installed again Revanced 19.16 from this repo and then it worked. Also planning on installing Zygisk Detach so Google won't mess up my setup.
> 
> Can you share in details what you did please? Because I disabled Google Play Store and removed YouTube using Lucky Patcher but whenever I reboot I find it again

Remove any Magisk modules regarding YouTube, then update YouTube to newest version using Google Play, then try to retrace my steps. Do you have YouTube installed as a system app? Do you have YouTube APK folder in "/data/app"?

**Comment by Othmane-ElAlami** [comment] 2024-09-07 01:46
> Remove any Magisk modules regarding YouTube, then update YouTube to newest version using Google Play, then try to retrace my steps. Do you have YouTube installed as a system app? Do you have YouTube APK folder in "/data/app"?

After updating it, I can now see it in /data/app but the result remains unchanged; it reverts to using /product/app after I uninstall it with Lucky Patcher.

**Comment by ptrnsg** [comment] 2024-09-08 13:25
@sudanking I had a similar problem - the YouTube app kept reappearing and wouldn't install/uninstall properly - which meant none of the suggestions above worked. Even after I uninstalled it, the Magisk module would still see a higher Solving that specific problem was key, so:

1. Clear the cache in Google Play Store and Google Play Services.
2. Reboot (now YouTube should appear as a properly installed app)
4. 'Debloat' Youtube (or Lucky Patcher et al)
5. Install the revanced-magisk-module.

That worked for me.

**Comment by spicediablo** [comment] 2024-09-14 04:32
This is how i fixed mine, i scrolled through the older release and found that there is v19.25.xx and i managed to install it successfully. Remember to uninstall the updates to youtube first before attempting this.

![github](https://github.com/user-attachments/assets/a17cc68d-3444-4fd9-983c-ac29db0c1f0f)

**Comment by waterpolo** [comment] 2024-09-22 18:57
Last week I have update my Samsung S23 to OneUI 6.1.1. With this update the ROM has default YouTube version 19.17.34. Therefor I can't install the magisk module version 19.16.39.
Is there a solution or do I need to wait that module release is upgraded? Is this in roadmap?

**Comment by spicediablo** [comment] 2024-09-22 23:29
> Last week I have update my Samsung S23 to OneUI 6.1.1. With this update the ROM has default YouTube version 19.17.34. Therefor I can't install the magisk module version 19.16.39. Is there a solution or do I need to wait that module release is upgraded? Is this in roadmap?
> 
> Edit: Install Debloater, see link in post above, and remove YouTube as system app. Then install magisk module and reboot phone. The modified 19.16.39 is installed.

Can you please provide the link for the debloater? I can't seem to find from previous post. It'll be good if you can also post some screenshots of the debloater. 

Thanks.

**Comment by waterpolo** [comment] 2024-09-23 17:47
> > Last week I have update my Samsung S23 to OneUI 6.1.1. With this update the ROM has default YouTube version 19.17.34. Therefor I can't install the magisk module version 19.16.39. Is there a solution or do I need to wait that module release is upgraded? Is this in roadmap?
> > Edit: Install Debloater, see link in post above, and remove YouTube as system app. Then install magisk module and reboot phone. The modified 19.16.39 is installed.
> 
> Can you please provide the link for the debloater? I can't seem to find from previous post. It'll be good if you can also post some screenshots of the debloater.
> 
> Thanks.
see the post (link) below:
https://github.com/j-hc/revanced-magisk-module/issues/489#issuecomment-2313237288

Additional I have installed Zygisk-detach to detach YouTube from Play Store.

**Comment by spicediablo** [comment] 2024-09-24 02:06
> > > Last week I have update my Samsung S23 to OneUI 6.1.1. With this update the ROM has default YouTube version 19.17.34. Therefor I can't install the magisk module version 19.16.39. Is there a solution or do I need to wait that module release is upgraded? Is this in roadmap?
> > > Edit: Install Debloater, see link in post above, and remove YouTube as system app. Then install magisk module and reboot phone. The modified 19.16.39 is installed.
> > 
> > 
> > Can you please provide the link for the debloater? I can't seem to find from previous post. It'll be good if you can also post some screenshots of the debloater.
> > Thanks.
> > see the post (link) below:
> > [#489 (comment)](https://github.com/j-hc/revanced-magisk-module/issues/489#issuecomment-2313237288)
> 
> Additional I have installed Zygisk-detach to detach YouTube from Play Store.

I can't seem to get it to work even after using debloater. Would you have clearer instructions please?

 thanks.

**Comment by spicediablo** [comment] 2024-09-24 07:38
> @sudanking I had a similar problem - the YouTube app kept reappearing and wouldn't install/uninstall properly - which meant none of the suggestions above worked. Even after I uninstalled it, the Magisk module would still see a higher version of YouTube already installed. Solving that specific problem was key, so:
> 
> 1. Clear the cache in Google Play Store and Google Play Services.
> 2. Reboot (now YouTube should appear as a properly installed app)
> 3. 'Debloat' Youtube (or Lucky Patcher et al)
> 4. Install the revanced-magisk-module.
> 
> That worked for me.

Can you please suggest which app or method did you use for debloating? What model of phone are you using?

**Comment by Umib00zu** [comment] 2024-09-27 21:55
I got exactly the same problem when I updated my samsung tab to 6.1.1. It’s very strange that I see no trace of a youtube app on titanium. But when I clear cache of google play and service.... it appear! So I used zygisk-detach , I unstalled it again... but I keep this message error. 
I’m too lazy, I get back to the « -all » version with microG.

**Comment by waterpolo** [comment] 2024-09-28 08:36
> I got exactly the same problem when I updated my samsung tab to 6.1.1. It’s very strange that I see no trace of a youtube app on titanium. But when I clear cache of google play and service.... it appear! So I used zygisk-detach , I unstalled it again... but I keep this message error. I’m too lazy, I get back to the « -all » version with microG.

Did you remove YouTube as system, with Debloater or other app? That is the most important step.

**Comment by spicediablo** [comment] 2024-09-28 08:39
> > I got exactly the same problem when I updated my samsung tab to 6.1.1. It’s very strange that I see no trace of a youtube app on titanium. But when I clear cache of google play and service.... it appear! So I used zygisk-detach , I unstalled it again... but I keep this message error. I’m too lazy, I get back to the « -all » version with microG.
> 
> Did you remove YouTube as system, with Debloater or other app? That is the most important step.

Do you have some screenshots to show? It would help a lot. For debloater app, I just select uninstall.

**Comment by waterpolo** [comment] 2024-09-28 09:06
> > > I got exactly the same problem when I updated my samsung tab to 6.1.1. It’s very strange that I see no trace of a youtube app on titanium. But when I clear cache of google play and service.... it appear! So I used zygisk-detach , I unstalled it again... but I keep this message error. I’m too lazy, I get back to the « -all » version with microG.
> > 
> > 
> > Did you remove YouTube as system, with Debloater or other app? That is the most important step.
> 
> Do you have some screenshots to show? It would help a lot. For debloater app, I just select uninstall.

![Screenshot_20240928_105812_De-Bloater](https://github.com/user-attachments/assets/56b4d2b4-a98e-4d2c-8f19-12ee56069cd6)
When you remove YouTube from Product then this will be displayed in Inactive tab, see screenshot.
Then clear Play Store and run the Zygisk-detach script to block update. Reboot device and then you could install the Magisk YouTube Revanced module.

**Comment by spicediablo** [comment] 2024-09-28 09:14
> > > > I got exactly the same problem when I updated my samsung tab to 6.1.1. It’s very strange that I see no trace of a youtube app on titanium. But when I clear cache of google play and service.... it appear! So I used zygisk-detach , I unstalled it again... but I keep this message error. I’m too lazy, I get back to the « -all » version with microG.
> > > 
> > > 
> > > Did you remove YouTube as system, with Debloater or other app? That is the most important step.
> > 
> > 
> > Do you have some screenshots to show? It would help a lot. For debloater app, I just select uninstall.
> 
> ![Screenshot_20240928_105812_De-Bloater](https://private-user-images.githubusercontent.com/682624/371744416-56b4d2b4-a98e-4d2c-8f19-12ee56069cd6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MTUwNDQsIm5iZiI6MTcyNzUxNDc0NCwicGF0aCI6Ii82ODI2MjQvMzcxNzQ0NDE2LTU2YjRkMmI0LWE5OGUtNGQyYy04ZjE5LTEyZWU1NjA2OWNkNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOFQwOTEyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWNjMzRmNDRiMTY1ZDBhMWQ2OTIzYTdlNGIwYjU1NzcxYzcxN2ZjYTI2MGNlNDA0ZmRjNjAyYjY2YWNlZjVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EnEe88Q4R_BtYD-ONjzTLcjJ2Sd63eXSXAup1ghaes0) When you remove YouTube from Product then this will be displayed in Inactive tab, see screenshot. Then clear Play Store and run the Zygisk-detach script to block update. Reboot device and then you could install the Magisk YouTube Revanced module.

But the problem is that even without update, the base youtube version is higher than revanced and this will cause the error.

**Comment by waterpolo** [comment] 2024-09-28 09:53
Try to restore the system app and see if you uninstall any YouTube update in Google Play Store. Clear the Play Store data. Reboot device and try again all steps. I have also done twice before it was working. 
Btw I didn't use Lucky patcher and didn't clear Google Services.

**Comment by spicediablo** [comment] 2024-09-28 10:05
> Try to restore the system app and see if you uninstall any YouTube update in Google Play Store. Clear the Play Store data. Reboot device and try again all steps. I have also done twice before it was working. Btw I didn't use Lucky patcher and didn't clear Google Services.

Thanks @waterpolo , it works! Turns out i did not uninstall the updates. So the sequence is
1)Remove previously installed revanced/vanced youtube
2)Uninstall youtube updates
3)Debloat using debloat app
4)Reboot and install lower version vanced youtube.

**Comment by waterpolo** [comment] 2024-09-28 12:00
> > Try to restore the system app and see if you uninstall any YouTube update in Google Play Store. Clear the Play Store data. Reboot device and try again all steps. I have also done twice before it was working. Btw I didn't use Lucky patcher and didn't clear Google Services.
> 
> Thanks @waterpolo , it works! Turns out i did not uninstall the updates. So the sequence is 1)Remove previously installed revanced/vanced youtube 2)Uninstall youtube updates 3)Debloat using debloat app here(https://github.com/sunilpaulmathew/De-Bloater) 4)Reboot and install lower version vanced youtube.

5) Clear Google Play Store data
6) Use Zygisk-detach module script in Terminal to detach YouTube from Play Store

**Comment by spicediablo** [comment] 2024-09-28 12:03
> > > Try to restore the system app and see if you uninstall any YouTube update in Google Play Store. Clear the Play Store data. Reboot device and try again all steps. I have also done twice before it was working. Btw I didn't use Lucky patcher and didn't clear Google Services.
> > 
> > 
> > Thanks @waterpolo , it works! Turns out i did not uninstall the updates. So the sequence is 1)Remove previously installed revanced/vanced youtube 2)Uninstall youtube updates 3)Debloat using debloat app here(https://github.com/sunilpaulmathew/De-Bloater) 4)Reboot and install lower version vanced youtube.
> 
> 5. Clear Google Play Store data
> 6. Use Zygisk-detach module script in Terminal to detach YouTube from Play Store

For step 6, my youtube has been detached even before all the steps started.

**Comment by j-hc** [comment] 2024-10-06 09:06
fixed 1a7678c

**Comment by spicediablo** [comment] 2024-10-06 10:58
> fixed [1a7678c](https://github.com/j-hc/revanced-magisk-module/commit/1a7678c6f5c957445d23fab0367fdc8db389c473)

Do you mean i don't need to debloat now before installing?

**Comment by sudanking** [comment] 2024-10-06 19:31
> fixed 1a7678c

Still same problem 
Can not install it ![Screenshot_2024-10-06-23-29-29-37_26ccd656f4ada08d09da6514b90ed2c0.jpg](https://github.com/user-attachments/assets/00bc7ff1-e87e-41de-b655-b02e3b6c9b33)

**Comment by j-hc** [comment] 2024-10-06 19:34
> > fixed 1a7678c
> 
> Still same problem 
> Can not install it ![Screenshot_2024-10-06-23-29-29-37_26ccd656f4ada08d09da6514b90ed2c0.jpg](https://github.com/user-attachments/assets/00bc7ff1-e87e-41de-b655-b02e3b6c9b33)
> 
> 

new modules arent even built yet. what are you talking about

**Comment by spicediablo** [comment] 2024-10-07 01:12
> > fixed [1a7678c](https://github.com/j-hc/revanced-magisk-module/commit/1a7678c6f5c957445d23fab0367fdc8db389c473)
> 
> Still same problem Can not install it ![Screenshot_2024-10-06-23-29-29-37_26ccd656f4ada08d09da6514b90ed2c0.jpg](https://private-user-images.githubusercontent.com/434739/373974785-00bc7ff1-e87e-41de-b655-b02e3b6c9b33.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjM3OTgsIm5iZiI6MTcyODI2MzQ5OCwicGF0aCI6Ii80MzQ3MzkvMzczOTc0Nzg1LTAwYmM3ZmYxLWU4N2UtNDFkZS1iNjU1LWIwMmUzYjZjOWIzMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwMTExMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzhkNmNjNTgwOTY3NGZlNGFiOWMyZTBiMGEzZjc4ZGI4ZWJmMGQ5Y2NjNmNmOTE1ZDA3ZTU5NDU1NjlhZDExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yb8qUTI4ZLeqxH_Ei0tRY_SJgmojG6foaF46eTOSZAA)

Perhaps try when there is a new version. The newest version was released 5 days ago. Give him some time :)

**Comment by stBlackD** [comment] 2024-10-16 03:44
Same error after updating to Android 15

**Comment by waterpolo** [comment] 2024-10-16 04:42
> Same error after updating to Android 15

Do you use the standard YouTube Vanced Magisk module? This isn't released with the latest 'fix'.

**Comment by stBlackD** [comment] 2024-10-16 05:01
Yes, i`m used last release from this repo. Install release on 6 jul fixed my issue.

**Comment by thatsupnow** [comment] 2024-10-18 17:03
Getting the same install failed error on Android 15 Pixel 8. Went back and installed July 5 release and works fine

**Comment by Hengen42** [comment] 2024-10-19 07:27
> [Lucky Patcher'ı](https://www.luckypatchers.com/download/) kullanarak kaldırmayı deneyin[](https://www.luckypatchers.com/download/)

this worked for me thank you.

**Closed** 2024-10-20 11:18 UTC

**Comment by j-hc** [comment] 2024-10-20 13:21
7aad796

**Comment by fxrstor** [comment] 2026-04-22 08:58
Uninstalling updates of YouTube app (from PlayStore) worked for me.
