### ISSUE TITLE
Twitter app crashed after reboot

### ISSUE THREAD

**Issue by tendor09** [j-hc/revanced-magisk-module#130] opened 2022-12-29 13:38 UTC
Everytime I update the Youtube Revanced Magisk module and restart the phone the twitter app is crashing.
The ony solution that i have found - uninstall Twitter app (which has a quite strange App info Description ike "Anyone can listen, including people not logged in to Twitter...."), and reinstall it from Google Play.
I really do not understand why the Ytube revanced Magisk module is affecting Twitter app and how to avoid this behaviour.

**Comment by j-hc** [comment] 2022-12-29 17:24
what are the exact steps to reproduce the issue you are having?

**Comment by tendor09** [comment] 2022-12-29 18:51
1. Download your Revanced Magisk module and flash via Magisk. 
2. After some time, hit the Update Button to update the module
3. Restart the phone
4. Twitter app has a different name (indicated in the first post) and it is crashing every time i try to acces it.

**Comment by j-hc** [comment] 2022-12-29 20:43
what module? twitter? or is yt module causing twitter to crash?

**Comment by Vucko130** [comment] 2022-12-30 02:21
facing the same problem. Youtube is not crashing after the twitter crash. After restart if i go to app info it shows twitter name changed to "Do you know when you first registered on twitter?"

**Comment by Vucko130** [comment] 2022-12-30 02:54
![Screenshot_20221230-085151_Settings](https://user-images.githubusercontent.com/92352731/210029744-e0407f2c-f162-46e0-9da4-3bc7cd67bc29.png)
I have attached a screenshot of the app name change from twitter to that weird thing.

**Comment by tendor09** [comment] 2022-12-30 19:25
> 
Yes, after: 
1) updating the magisk youtube revanced module to the last version
2) phone restart,
everytime I get twitter crash, and twitter app has a stupid name, just like [Vucko130](https://github.com/Vucko130) indicated, in the previous screenshot.

**Comment by j-hc** [comment] 2023-01-01 21:41
does it only happen when youtube version is updated during module flash?

**Comment by tendor09** [comment] 2023-01-01 21:58
I noticed the Twitter issue every time I restart the phone immediately **or** some time after Youtube Revanced Magisk module update.

**Comment by j-hc** [comment] 2023-01-10 16:08
I dont have much to do tbh. I cant reproduce the issue.

**Comment by j-hc** [comment] 2023-02-24 17:16
This is most likely caused by force reboots whilst the mount is present, installation of the modules from third party module managers, play store updating the apps. Only solution is to clean install so im closing the issue.

**Closed by j-hc** 2023-02-24 17:16 UTC
